### ISSUE TITLE
Deprecated task execution handler

### ISSUE THREAD

**Issue by Thilas** [dev-maxima/nsis-extension#2]
I recently started to get this sort of warnings when running your tasks:

##[warning]Task 'nsis' (1.1.2) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Could you please have a look? Or if you prefer, I can give it a try and submit a pull request.

FYI, here are the kind of changes that are required: https://github.com/cake-build/cake-vso/pull/49/files

Thanks.

**Comment by darkurse** [comment]
Seems to be working now. Sorry it took so long

**Comment by Thilas** [comment]
So long!? Thanks for being so quick! I'll try to test this next week. Thank again.
